// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwtEVrNOH25Pf8DugqCS_YFz-sx_A3-3I',
    appId: '1:1049661667501:web:17ddda5c54ad1990b96e24',
    messagingSenderId: '1049661667501',
    projectId: 'e-commerce-3555f',
    authDomain: 'e-commerce-3555f.firebaseapp.com',
    storageBucket: 'e-commerce-3555f.firebasestorage.app',
    measurementId: 'G-LHS327HXVX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDo1B6cx0_117rJs7Jxz0AfkvK4GLLqUck',
    appId: '1:1049661667501:android:77b9b58f0ce3cef1b96e24',
    messagingSenderId: '1049661667501',
    projectId: 'e-commerce-3555f',
    storageBucket: 'e-commerce-3555f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3209XbvictSPvBQSJ31A5F9s_sE_g5Ww',
    appId: '1:1049661667501:ios:8bdf6996857a8c4cb96e24',
    messagingSenderId: '1049661667501',
    projectId: 'e-commerce-3555f',
    storageBucket: 'e-commerce-3555f.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3209XbvictSPvBQSJ31A5F9s_sE_g5Ww',
    appId: '1:1049661667501:ios:8bdf6996857a8c4cb96e24',
    messagingSenderId: '1049661667501',
    projectId: 'e-commerce-3555f',
    storageBucket: 'e-commerce-3555f.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwtEVrNOH25Pf8DugqCS_YFz-sx_A3-3I',
    appId: '1:1049661667501:web:ef9d6290d0023e97b96e24',
    messagingSenderId: '1049661667501',
    projectId: 'e-commerce-3555f',
    authDomain: 'e-commerce-3555f.firebaseapp.com',
    storageBucket: 'e-commerce-3555f.firebasestorage.app',
    measurementId: 'G-RNPPGKNN04',
  );
}
